nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/opt:/opt

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - ~/opt:/opt

memcache:
    build: ./memcache
    ports:
      - "11211:11211"

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

redis:
    build: ./redis
    ports:
      - "6379:6379"


sftp:
    build: ./sftp
    volumes:
        - ~/opt:/home/ftpuser/opt
        - ~/.ssh:/home/ftpuser/.ssh
    ports:
        - "2222:22"
    command: ftpuser:123456:1001
