nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/opt:/opt

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - ~/opt:/opt

memcache:
    build: ./memcache
    ports:
      - "11211:11211"

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

redis:
    build: ./redis
    ports:
      - "6379:6379"


sftp:
    build: ./sftp
    volumes:
        - ~/opt:/home/ftpuser/opt
        - ~/.ssh:/home/ftpuser/.ssh
    ports:
        - "2222:22"
    command: ftpuser:123456:1001

shadowsocks-server:
  build: ./shadowsocks
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - PASSWORD=5ouMnqPyzseL
  restart: always

shadowsocks-client:
  build: ./shadowsocks
  command: >
  #SERVER_ADDR
    ss-local -s 1.2.3.4
             -p 8388
             -m aes-256-cfb
             -k 5ouMnqPyzseL
             -b 0.0.0.0
             -l 1080
             -t 300
             --fast-open
  ports:
    - "1080:1080"
  restart: always

shadowsocks-client-arm:
  build: ./shadowsocks/arm
  ports:
    - "1080:1080"
  environment:
    #SERVER_ADDR
    - SERVER_ADDR=1.2.3.4
    - PASSWORD=5ouMnqPyzseL
  restart: always
