FROM atmoz/sftp

#ADD  users.conf      /etc/sftp-users.conf

#sftp -P 2222 ftpuser@104.236.162.252
#RUN groupadd ftpuser
#RUN useradd -m ftpuser -g ftpuser -s /usr/sbin/nologin
#RUN chown ftpuser:ftpuser /home/ftpuser
#RUN chown -R ftpuser.ftpuser /home/ftpuser/opt

#RUN chmod 755 /home/ftpuser
